CREATE TABLE IF NOT EXISTS configuracoes (
  chave VARCHAR(100) NOT NULL,
  valor LONGTEXT NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (chave)
);
